// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoDbRole = "go_db_role"

// GoDbRole mapped from table <go_db_role>
type GoDbRole struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:'primary Key is ID'" json:"id"` // 'primary Key is ID'
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	RoleName  string         `gorm:"column:role_name" json:"role_name"`
	RoleNote  string         `gorm:"column:role_note" json:"role_note"`
}

// TableName GoDbRole's table name
func (*GoDbRole) TableName() string {
	return TableNameGoDbRole
}
