// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoDbUser = "go_db_user"

// GoDbUser mapped from table <go_db_user>
type GoDbUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	UserName  string         `gorm:"column:user_name" json:"user_name"`
	IsActive  bool           `gorm:"column:is_active" json:"is_active"`
}

// TableName GoDbUser's table name
func (*GoDbUser) TableName() string {
	return TableNameGoDbUser
}
